### ISSUE TITLE
Navico Link on front page

### ISSUE THREAD

**Issue by Dirk--** [OpenSeaMap/website#9]
"Lowrance, Simrad, B&G EU-weite Abdeckung"
links to:
http://wiki.openstreetmap.org/wiki/DE:OpenSeaMap_and_Garmin_nautical_chart_plotter
should link to:
http://wiki.openseamap.org/wiki/De:Navigation_program#Navico

**Comment by Dirk--** [comment]
Seems to be fixed, pointing to http://wiki.openstreetmap.org/wiki/AT5-OpenSeaMap-Chart_for_Lowrance_Simrad_B%26G now.

**Comment by ehrenfeu** [comment]
Hum, apparently someone reacted to this report and adjusted it but didn't close the ticket here. I'm doing this right now.
